---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true

env:
  # we recommend testing LTS's and latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - phantomjs --version

install:
  - yarn install --no-lockfile
  - yarn run bower -- install

script:
  # Usually, it's ok to finish the test scenario without reverting to the
  # addon's original dependency state, skipping "cleanup".
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup

notifications:
  email: false
  slack:
    on_success: change
    on_failure: always
    rooms:
    - secure: iJgStcKlpjxRESM8b7dyx4wuJR49dDXlVTtCupru/4SgTIF9qC+5BoV9Px7GFXD1bB7aGQKh2MY7jBT9QgQcZYJVa70pR10EOoR4dVwYsvzjpF2kYD3WXnDH8OX61ASSH1iBpYP8KzQ4Y00j/5FLgqErxVN6ykcSQvwUL2fsE/I=
